"""Domain-agnostic guardrail verdicts and reason codes."""
from __future__ import annotations

from enum import Enum


class Verdict(str, Enum):
    ALLOW = "allow"
    BLOCK = "block"
    REDACT = "redact"
    ESCALATE = "escalate"
    WARN = "warn"


class ReasonCode(str, Enum):
    POLICY_VIOLATION = "POLICY_VIOLATION"
    SAFETY_BLOCK = "SAFETY_BLOCK"
    INJECTION_DETECTED = "INJECTION_DETECTED"
    PII_DETECTED = "PII_DETECTED"
    RATE_LIMITED = "RATE_LIMITED"
    INPUT_TOO_LONG = "INPUT_TOO_LONG"
    OUTPUT_INVALID = "OUTPUT_INVALID"
    ESCALATED = "ESCALATED"
    TOOL_DENIED = "TOOL_DENIED"
    TOOL_UNKNOWN = "TOOL_UNKNOWN"
    TOOL_NEEDS_APPROVAL = "TOOL_NEEDS_APPROVAL"
    TOOL_NOT_SANDBOXED = "TOOL_NOT_SANDBOXED"
    TOOL_SCOPE_DENIED = "TOOL_SCOPE_DENIED"
    TOOL_PARAM_DENIED = "TOOL_PARAM_DENIED"
    TOOL_DANGEROUS_ARGUMENT = "TOOL_DANGEROUS_ARGUMENT"
    TOOL_PATH_ESCAPE = "TOOL_PATH_ESCAPE"
    CUSTOM = "CUSTOM"
